# Generated by Django 6.0.7 on 2026-07-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('citizen_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('ward', models.IntegerField()),
                ('category', models.CharField(choices=[('Road', 'Road'), ('Water', 'Water'), ('Electricity', 'Electricity'), ('Sanitation', 'Sanitation'), ('Education', 'Education'), ('Health', 'Health'), ('Agriculture', 'Agriculture'), ('Other', 'Other')], max_length=50)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='complaints/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('reply', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WardOfficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_number', models.IntegerField(choices=[(1, 'वडा नं. १'), (2, 'वडा नं. २'), (3, 'वडा नं. ३'), (4, 'वडा नं. ४'), (5, 'वडा नं. ५'), (6, 'वडा नं. ६'), (7, 'वडा नं. ७'), (8, 'वडा नं. ८'), (9, 'वडा नं. ९')])),
                ('full_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
