# Generated by Django 6.0.7 on 2026-08-02 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0005_complaint_resolved_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('purpose', models.CharField(blank=True, choices=[('registration', 'Registration'), ('status_change', 'Status change')], max_length=30)),
                ('success', models.BooleanField(default=False)),
                ('provider_response', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='complaint.complaint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
