# Generated by Django 6.0.7 on 2026-08-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0007_complaint_hidden_by_office_complaint_hidden_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='citizen_confirmed',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='dispute_reason',
            field=models.TextField(blank=True),
        ),
    ]
