# Generated by Django 6.0.7 on 2026-08-02 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0008_complaint_citizen_confirmed_complaint_confirmed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('used', models.BooleanField(default=False)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='smslog',
            name='purpose',
            field=models.CharField(blank=True, choices=[('registration', 'Registration'), ('status_change', 'Status change'), ('login_code', 'Login code')], max_length=30),
        ),
        migrations.AddField(
            model_name='upvote',
            name='citizen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='complaint.citizen'),
        ),
        migrations.AddConstraint(
            model_name='upvote',
            constraint=models.UniqueConstraint(condition=models.Q(('citizen__isnull', False)), fields=('complaint', 'citizen'), name='unique_upvote_per_citizen'),
        ),
    ]
