# Generated by Django 6.0.7 on 2026-08-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0013_wardofficial_drop_local_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='citizen',
            name='ward',
            field=models.IntegerField(blank=True, choices=[(1, 'वडा नं. १'), (2, 'वडा नं. २'), (3, 'वडा नं. ३'), (4, 'वडा नं. ४'), (5, 'वडा नं. ५'), (6, 'वडा नं. ६'), (7, 'वडा नं. ७'), (8, 'वडा नं. ८'), (9, 'वडा नं. ९')], null=True),
        ),
    ]
